### ISSUE TITLE
I don't know how to use 'lemma' environment...

### ISSUE THREAD

**Issue by tesSer16** [gijs-pennings/latex-homework#4]
Hello, I am a Freshman student who is learning Latex at first.

I think I know how to use 'definition' environment by \begin and \end,
but I couldn't use the 'lemma' environment for the same work...
Can I ask you how to use the environment..?

I'm looking forward to your reply.
Thank you.

**Comment by gijs-pennings** [comment]
I can't reproduce your issue; for me `\begin{lemma} ... \end{lemma}` is working fine. Have a look at [the template](https://github.com/gijs-pennings/latex-homework/blob/278445d2df3f79be27b3fbeafc5e1f6475833b59/main.tex#L20) and try replacing `definition` by `lemma` directly.

**Comment by tesSer16** [comment]
Thank you for replying.
I could solve the problem for your solution.
But, I still don't know what was the matter...
And I really appreciate that I could learn a lot from your template!
