### ISSUE TITLE
Appendix for the document class

### ISSUE THREAD

**Issue by Zhuoyue-Huang** [gijs-pennings/latex-homework#5]
Hi, I am a beginner at latex. And I really like the style of your page! The minor thing that bothers me a bit is that I cannot add appendices to the template, which is quite annoying. I try to customise it and I failed :(. It would be really nice if you could give me some direction about how to add an appendix in a new document class. 

Thanks in advance!

**Comment by gijs-pennings** [comment]
I'm not completely sure what you mean. There's a simple `\appendix` command that resets the numbering of sections and makes it alphabetic. There's a small example [here](https://texfaq.org/FAQ-appendix).

**Comment by Zhuoyue-Huang** [comment]
Oops sorry, it is just me being stupid. I accidentally used \chapter in the appendix, which should be \section. Thanks for your suggestions!
