### ISSUE TITLE
NewTheorem environments only showing up as Definition

### ISSUE THREAD

**Issue by philippezwietering** [gijs-pennings/latex-homework#6]
Hi,

Thanks for providing this template, I think it's great! I have one issue however; I can't get the NewTheorem environments apart from definition working. When using your class file, I only get the environments shown as Definition, not as their correct theorem-like counterpart.

Code example, together with my LaTeX output (I'm using pdflatex on Arch, with most texlive packages installed):
```tex
\begin{document}

\exercise*[0.3.6]
\begin{enumerate}[label=\emph{\alph*)}]
    \item Wanting to show:
        $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$

        In order to prove this equivalence, we have to prove the implication both ways. We use two lemmas for this.

        \begin{lemma}
            $A \cap (B \cup C) \implies (A \cap B) \cup (A \cap C)$

            Let $x \in A \cap (B \cup C)$.
        \end{lemma}
        \begin{definition}
            Test, this is a definition.

            Also, test some random stuff to see if .cls is imported correctly:

            * should be a cdot.

            $\N$ are the natural numbers, whereas $\R$ are the reals.
        \end{definition}
    \item
\end{enumerate}

\begin{corollary}
    This should be a corollary.
\end{corollary}

\begin{proposition}
    This is a proposition.
\end{proposition}

\begin{theorem}
    This line is so important, it should be a theorem!
\end{theorem}

\end{document}
``` 

![image](https://github.com/gijs-pennings/latex-homework/assets/14801363/1e649981-41c4-40b7-8ea8-bd20d2983826)

Am I using the command wrong, or is it just not working as I expected? Just using `\lemma` also doesn't work. I also saw #4, but that suggests that I am using it correctly. I would very much like to use this feature, so help would be much appreciated!

Regards

**Comment by philippezwietering** [comment]
Oh btw, I see now that the star isn't a cdot, but that's because it wasn't written inside math mode. It works just fine when it's done correctly.

**Comment by gijs-pennings** [comment]
Thanks for the bug report! It's indeed not working as expected; I think I introduced this bug in fc26a0c (oops). I've just pushed a fix. Please let me know if this works.

**Comment by philippezwietering** [comment]
Yes, that fixed it! Great, thank you!
